In [2]:
# System imports
import os
import sys
from pprint import pprint as pp

# External imports
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
from torch_scatter import scatter_add

# Limit CPU usage on Jupyter
os.environ['OMP_NUM_THREADS'] = '4'

# Pick up local packages
sys.path.append('..')

# Local imports
from trainers import get_trainer
from nb_utils import (load_config_file, load_config_dir, load_summaries,
                      plot_train_history, get_test_data_loader,
                      compute_metrics, plot_metrics, draw_sample_xy)

In [4]:
d_index = np.array([[1,1,2,2,5,3,4],[2,5,3,4,4,6,6]])

In [6]:
start, end = d_index

In [10]:
start

array([1, 1, 2, 2, 5, 3, 4])

In [11]:
end

array([2, 5, 3, 4, 4, 6, 6])

In [16]:
np.isin(start, end)

array([False, False,  True,  True,  True,  True,  True])

In [15]:
np.nonzero(np.isin(start, end))

(array([2, 3, 4, 5, 6]),)

In [14]:
np.nonzero(np.isin(end, start))

(array([0, 1, 2, 3, 4]),)

In [25]:
[key for key, val in enumerate(start) 
                      if val in set(end)] 

[2, 3, 4, 5, 6]

In [26]:
[key for key, val in enumerate(end) 
                      if val in set(start)] 

[0, 1, 2, 3, 4]

In [34]:
[(key1,key2) for key1, val1 in enumerate(start) for key2, val2 in enumerate(end) if val1 == val2]

[(2, 0), (3, 0), (4, 1), (5, 2), (6, 3), (6, 4)]